# SITE CONFIGURATION
title: Halcyonic Research # your site title
author: Josiah Bryan # You :P
description: > # Meta description of Homepage
  This is the main site for Halcyonic Security Research where I try to post on interesting security (or random) topics
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://halcyonic.net" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Josiah Bryan
  links:
    - https://twitter.com/halcy0nic
    - https://github.com/Halcy0nic

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Our greatest accomplishments cannot be behind us, because our destiny lies above us. -Interstellar

hero_img: posts/maldives_summer.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: support@halcyonic.us # email for form submission

twitter_username: Halcy0nic # replace with your_twitter_username or comment to remove link from footer
github_username:  Halcy0nic # replace with your_github_username or comment to remove link from footer
#instagram_username:  # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: halcy0nic # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-THD23HL # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
